version: '3.0'

services:
  db:
    image: postgres:9.6-alpine
    container_name: exmonit_db
    hostname: exmonit_db
    env_file: .env
    volumes:
      - /srv/postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  exmonit:
    depends_on:
      - "db"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exmonit
    hostname: exmonit
    env_file: .env
    volumes:
      - ./configs/config.yml:/srv/config.yml
    ports:
      - "8088:8080"
  prometheus:
    depends_on:
      - "exmonit"
    image: prom/prometheus:v2.14.0
    container_name: exmonit_prom
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9090"